trigger: none
  # batch: 'true'
  # branches:
  #   include: [ master ]
  # tags:
  #   exclude: [ NoBuild ]

stages:
# S2 - Sub Deploy (G0)
# - stage: S3_Sub
#   variables:
#     APP : ADF
#     ENV: S3
#     PREFIX : AZC1
#   jobs:
#   - job: RG_RBAC
#     pool:
#       vmImage: windows-2019
#     steps:
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'AZC1-ADF-RG-G0-AZC1-ADF-RG-G0'
#         ScriptType: 'FilePath'
#         ScriptPath: 'AZC1-ADF-RG-P0/release/AzDeploy.ps1'
#         ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG" -SubscriptionDeploy -FullUpload'
#         FailOnStandardError: true
#         azurePowerShellVersion: 'LatestVersion'

# S1 - RG Deploy
- stage: S3_RG
  variables:
    APP : ADF
    ENV: S3
    PREFIX : AZC1
  jobs:
  - job: Initial_S3
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'AZC1-ADF-RG-G0-AZC1-ADF-RG-S3'
        ScriptType: 'FilePath'
        ScriptPath: 'AZC1-ADF-RG-P0/release/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(Prefix) -stage "ALL"'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'