# This is a basic workflow to help you get started with Actions

name: Deploy_AEU2_BRW_HUB_RG_P0

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  # push:
  #   branches: [dev]
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APP: HUB
  ENV: P0
  PREFIX: AEU2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  EnvironmentDeploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add wait on concurrent workflows executing via https://github.com/marketplace/actions/action-turnstyle
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AEU2_BRW_HUB_RG_G0}}
          enable-AzPSSession: true

      - name: G0_Sub
        uses: Azure/powershell@v1
        with:
          inlineScript: ./ADF/release-az/AzDeploy.ps1 -app $env:app -env $env:env -Prefix $env:prefix -stage "sub-InitialRG" -FullUpload
          azPSVersion: latest

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AEU2_BRW_HUB_RG_P0}}
          enable-AzPSSession: true

      - name: P0_RG
        uses: Azure/powershell@v1
        with:
          inlineScript: ./ADF/release-az/AzDeploy.ps1 -app $env:app -env $env:env -Prefix $env:prefix -stage "ALL"
          azPSVersion: latest
